import {
  HOST_V1_HASH,
  HOST_V1_MANIFEST,
  HOST_V2_HASH,
  HOST_V2_MANIFEST,
} from '@blue-quickjs/abi-manifest';
import type { AbiManifest } from '@blue-quickjs/abi-manifest';
import type { BuildFixtureDefinition } from './types.js';

export const CERTIFIER_FIXTURES: BuildFixtureDefinition[] = [
  {
    id: 'flagship-knowledge-pack',
    title: 'Flagship knowledge/compliance pack processor',
    kind: 'flagship',
    entryPath:
      'apps/ecosystem-certifier/fixtures/flagship/knowledge-pack-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v2',
    abiVersion: 2,
    abiManifestHash: HOST_V2_HASH,
    gasLimit: 8_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-chess',
    title: 'chess.js deterministic move legality',
    kind: 'positive',
    entryPath: 'libs/test-harness/fixtures/library-reuse/chess-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-base64',
    title: 'base64-js deterministic roundtrip',
    kind: 'positive',
    entryPath:
      'libs/test-harness/fixtures/library-reuse/binary-base64-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v2',
    abiVersion: 2,
    abiManifestHash: HOST_V2_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-noble-sha',
    title: '@noble/hashes deterministic digest',
    kind: 'positive',
    entryPath:
      'libs/test-harness/fixtures/library-reuse/binary-sha256-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v2',
    abiVersion: 2,
    abiManifestHash: HOST_V2_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-semver',
    title: 'semver constraint evaluation',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/semver-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-he',
    title: 'he deterministic HTML entity decode',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/he-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-path-to-regexp',
    title: 'path-to-regexp deterministic path match',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/path-to-regexp-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-fast-json-stable-stringify',
    title: 'fast-json-stable-stringify canonical output',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/fast-json-stable-stringify-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-json-logic-js',
    title: 'json-logic-js deterministic rule application',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/json-logic-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-crc32',
    title: 'crc-32 deterministic checksum calculation',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/crc32-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-tinyqueue',
    title: 'tinyqueue deterministic priority ordering',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/tinyqueue-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-fflate',
    title: 'fflate deterministic compression roundtrip',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/fflate-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-linkify-it',
    title: 'linkify-it deterministic URL extraction',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/linkify-it-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-markdown-it',
    title: 'markdown-it deterministic tokenization',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/markdown-it-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-escape-string-regexp',
    title: 'escape-string-regexp deterministic escaping',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/escape-string-regexp-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-fast-deep-equal',
    title: 'fast-deep-equal deterministic structure comparison',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/fast-deep-equal-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-stress-corpus',
    title: 'seeded stress corpus deterministic summary',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/stress-corpus-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-camelcase',
    title: 'camelcase deterministic normalization',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/camelcase-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-decamelize',
    title: 'decamelize deterministic token splitting',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/decamelize-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-fastest-levenshtein',
    title: 'fastest-levenshtein deterministic edit distance',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/fastest-levenshtein-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-dijkstrajs',
    title: 'dijkstrajs deterministic shortest path',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/dijkstrajs-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-spark-md5',
    title: 'spark-md5 deterministic hash digest',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/spark-md5-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-query-string',
    title: 'query-string deterministic parse/stringify',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/query-string-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-deepmerge',
    title: 'deepmerge deterministic object merge',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/deepmerge-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-sort-keys',
    title: 'sort-keys deterministic object ordering',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/sort-keys-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-array-move',
    title: 'array-move deterministic list reordering',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/array-move-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'red-diff-timers',
    title: 'diff package timer references are deterministically rejected',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/diff-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-yaml-date',
    title: 'yaml package date usage is deterministically rejected',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/yaml-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-graphlib-proxy',
    title: 'graphlib proxy usage is deterministically rejected',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/negative/graphlib-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-dynamic-import',
    title: 'dynamic import must be rejected at build stage',
    kind: 'negative',
    entryPath:
      'apps/ecosystem-certifier/fixtures/negative/dynamic-import-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-proxy',
    title: 'Proxy usage must be rejected at build stage',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/negative/proxy-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-math-random',
    title: 'Math.random usage must be rejected at build stage',
    kind: 'negative',
    entryPath:
      'apps/ecosystem-certifier/fixtures/negative/math-random-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-lodash-function-constructor',
    title: 'lodash-es root detection hits Function constructor in runtime',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/lodash-es-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: {
      stage: 'artifact_validation',
      errorCode: 'MODULE_EXPORT_MISSING',
      errorTag: 'vm/module_pack',
    },
  },
  {
    id: 'red-function-constructor',
    title:
      'Function constructor must fail deterministically in module-pack flow',
    kind: 'negative',
    entryPath:
      'apps/ecosystem-certifier/fixtures/negative/function-constructor-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: {
      stage: 'artifact_validation',
      errorCode: 'MODULE_EXPORT_MISSING',
      errorTag: 'vm/module_pack',
    },
  },
];

export function manifestForFixture(
  fixture: BuildFixtureDefinition,
): AbiManifest {
  return fixture.abiId === 'Host.v2' ? HOST_V2_MANIFEST : HOST_V1_MANIFEST;
}
