import {
  HOST_V1_HASH,
  HOST_V1_MANIFEST,
  HOST_V2_HASH,
  HOST_V2_MANIFEST,
} from '@blue-quickjs/abi-manifest';
import type { AbiManifest } from '@blue-quickjs/abi-manifest';
import type { BuildFixtureDefinition } from './types.js';

export const CERTIFIER_FIXTURES: BuildFixtureDefinition[] = [
  {
    id: 'flagship-knowledge-pack',
    title: 'Flagship knowledge/compliance pack processor',
    kind: 'flagship',
    entryPath: 'apps/ecosystem-certifier/fixtures/flagship/knowledge-pack-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v2',
    abiVersion: 2,
    abiManifestHash: HOST_V2_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'green-chess',
    title: 'chess.js deterministic move legality',
    kind: 'positive',
    entryPath: 'libs/test-harness/fixtures/library-reuse/chess-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-base64',
    title: 'base64-js deterministic roundtrip',
    kind: 'positive',
    entryPath: 'libs/test-harness/fixtures/library-reuse/binary-base64-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v2',
    abiVersion: 2,
    abiManifestHash: HOST_V2_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-noble-sha',
    title: '@noble/hashes deterministic digest',
    kind: 'positive',
    entryPath: 'libs/test-harness/fixtures/library-reuse/binary-sha256-entry.ts',
    profile: 'compat-binary-v1',
    abiId: 'Host.v2',
    abiVersion: 2,
    abiManifestHash: HOST_V2_HASH,
    gasLimit: 5_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-semver',
    title: 'semver constraint evaluation',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/semver-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'red-diff-timers',
    title: 'diff package timer references are deterministically rejected',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/diff-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'green-he',
    title: 'he deterministic HTML entity decode',
    kind: 'positive',
    entryPath: 'apps/ecosystem-certifier/fixtures/positive/he-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'green-path-to-regexp',
    title: 'path-to-regexp deterministic path match',
    kind: 'positive',
    entryPath:
      'apps/ecosystem-certifier/fixtures/positive/path-to-regexp-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'success' },
  },
  {
    id: 'red-dynamic-import',
    title: 'dynamic import must be rejected at build stage',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/negative/dynamic-import-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-proxy',
    title: 'Proxy usage must be rejected at build stage',
    kind: 'negative',
    entryPath: 'apps/ecosystem-certifier/fixtures/negative/proxy-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: { stage: 'builder_reject' },
  },
  {
    id: 'red-function-constructor',
    title: 'Function constructor must fail deterministically in module-pack flow',
    kind: 'negative',
    entryPath:
      'apps/ecosystem-certifier/fixtures/negative/function-constructor-entry.ts',
    profile: 'compat-general-v1',
    abiId: 'Host.v1',
    abiVersion: 1,
    abiManifestHash: HOST_V1_HASH,
    gasLimit: 1_000_000n,
    expect: {
      stage: 'artifact_validation',
      errorCode: 'MODULE_EXPORT_MISSING',
      errorTag: 'vm/module_pack',
    },
  },
];

export function manifestForFixture(fixture: BuildFixtureDefinition): AbiManifest {
  return fixture.abiId === 'Host.v2' ? HOST_V2_MANIFEST : HOST_V1_MANIFEST;
}
